repos:
  - repo: local
    hooks:
      - id: stylua-check
        name: Stylua check
        entry: stylua --check
        language: system
        types: [lua]

      - id: dprint-check
        name: Dprint check
        entry: dprint check --allow-no-files
        language: system
        types_or: [markdown, json, toml, yaml]
